import type { ServiceConfig } from "@/config/types";

/**
 * AI fulfillment for sellable services.
 *
 * When `ANTHROPIC_API_KEY` is set, the deliverable is generated by Claude via
 * the official SDK. Otherwise a deterministic simulated deliverable is returned
 * so the marketplace runs and demos with zero setup — consistent with the rest
 * of the app. The API key is read from the environment and never hardcoded.
 */

/** Default model for AI fulfillment. Overridable per service. */
const DEFAULT_MODEL = "claude-opus-4-8";

export interface FulfillmentResult {
  deliverable: string;
  /** Model id that produced it, or "simulated" in demo mode. */
  fulfilledBy: string;
  simulated: boolean;
}

export function isAiConfigured(): boolean {
  return Boolean(process.env.ANTHROPIC_API_KEY);
}

/** Render the service instructions + customer inputs into a single prompt. */
function buildPrompt(
  service: ServiceConfig,
  inputs: Record<string, string>,
): string {
  const lines: string[] = [service.instructions.trim(), ""];
  const entries = service.inputs
    .map((f) => {
      const value = (inputs[f.id] ?? "").trim();
      return value ? `- ${f.label}: ${value}` : null;
    })
    .filter(Boolean) as string[];
  if (entries.length) {
    lines.push("Customer-provided details:", ...entries);
  }
  return lines.join("\n");
}

/**
 * Produce the deliverable for a service request. Best-effort: on any error it
 * falls back to the simulated deliverable rather than throwing, so a purchased
 * service always returns something the customer can see.
 */
export async function fulfillService(
  service: ServiceConfig,
  inputs: Record<string, string>,
): Promise<FulfillmentResult> {
  if (!isAiConfigured()) {
    return simulate(service, inputs);
  }

  const model = service.model || DEFAULT_MODEL;
  const system =
    service.systemPrompt?.trim() ||
    "You are an expert service provider fulfilling a paid customer request. Produce a complete, polished, ready-to-use deliverable. Do not ask follow-up questions; work with the details provided.";

  try {
    // Lazily load the SDK so the app still builds/runs if it isn't installed.
    const specifier: string = "@anthropic-ai/sdk";
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const mod: any = await import(/* turbopackIgnore: true */ specifier);
    const Anthropic = mod.default ?? mod.Anthropic;
    const client = new Anthropic();

    const message = await client.messages.create({
      model,
      max_tokens: 8000,
      system,
      messages: [{ role: "user", content: buildPrompt(service, inputs) }],
    });

    const deliverable = (message.content ?? [])
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      .filter((b: any) => b.type === "text")
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      .map((b: any) => b.text)
      .join("\n")
      .trim();

    if (!deliverable) return simulate(service, inputs);
    return { deliverable, fulfilledBy: model, simulated: false };
  } catch {
    // Network/SDK/credential failure — degrade to the simulation.
    return simulate(service, inputs);
  }
}

/** Deterministic stand-in used in demo mode or when the live call fails. */
function simulate(
  service: ServiceConfig,
  inputs: Record<string, string>,
): FulfillmentResult {
  const provided = service.inputs
    .map((f) => {
      const v = (inputs[f.id] ?? "").trim();
      return v ? `- **${f.label}:** ${v}` : null;
    })
    .filter(Boolean)
    .join("\n");

  const deliverable = [
    "## Your deliverable (demo preview)",
    "",
    "This is a simulated deliverable generated without a live AI model. Set the",
    "`ANTHROPIC_API_KEY` environment variable to have this service fulfilled by",
    "Claude for real.",
    "",
    "**Task**",
    "",
    service.instructions.trim(),
    "",
    provided ? "**Details you provided**\n\n" + provided : "",
    "",
    "**Simulated result**",
    "",
    "A complete, polished result would appear here — tailored to the task and the",
    "details above — ready to download and use.",
  ]
    .filter((s) => s !== undefined)
    .join("\n");

  return { deliverable, fulfilledBy: "simulated", simulated: true };
}
